
/* CREATING FOUR CURRENCIES */

INSERT INTO CURRENCY_T001 (DESCRIPTION, NAME) VALUES( 'Soles', 'PEN');
INSERT INTO CURRENCY_T001 (DESCRIPTION, NAME) VALUES( 'Dolares', 'DOL');
INSERT INTO CURRENCY_T001 (DESCRIPTION, NAME) VALUES( 'Euros', 'EUR');
INSERT INTO CURRENCY_T001 (DESCRIPTION, NAME) VALUES( 'Pesos', 'PES');

/* RELATIONSHIP FOUR TYPES CURRENCIES */

INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (1, 2, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (1, 3, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (1, 4, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (2, 1, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (2, 3, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (2, 4, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (3, 1, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (3, 2, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (3, 4, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (4, 1, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (4, 2, now(), 0.5);
INSERT INTO EXCHANGE_RATE_T002 ( CURRENCY_BASE , CURRENCY_DESTINY , DATE , EXCHANGE_RATE ) VALUES (4, 3, now(), 0.5);

